
Construir un array de 4 filas, segun se indica: La primera fila estara formada por los numeros 6,7,9,15,22,34, los elementos de la segunda fila equivalen a la fila anterior multiplicada por 2, la tercera fila equivalen a la fila anterior menos 5 y la cuarta al cuadrado de la tercera fila.



In [1]:
import numpy as np

In [2]:
array = np.array([6,7,9,15,22,34])
array

array([ 6,  7,  9, 15, 22, 34])

In [3]:
array_2 = array * 2
array_3 = array_2 - 5
array_4 = array_3 ** 2


In [4]:
array_solucion = np.array([array, array_2, array_3, array_4])
array_solucion

array([[   6,    7,    9,   15,   22,   34],
       [  12,   14,   18,   30,   44,   68],
       [   7,    9,   13,   25,   39,   63],
       [  49,   81,  169,  625, 1521, 3969]])

In [5]:
pares = array_solucion[array_solucion % 2 == 0]
pares

array([ 6, 22, 34, 12, 14, 18, 30, 44, 68])

In [6]:
pares.size

9

 Resolver el siguiente sistema de ecuaciones, usando numpy

    x + 3y = 9

    6x + 3y = 5

In [8]:
a = np.array([[1,3],[6,3]])
a

array([[1, 3],
       [6, 3]])

In [14]:
b = np.array([[9],[5]])
b

array([[9],
       [5]])

In [15]:
np.linalg.solve(a,b)

array([[-0.8       ],
       [ 3.26666667]])