In [8]:
import numpy as np # pip install numpy

### Numpy, libreria para ciencia de datos

In [9]:
array_1d = np.array([1, 4, 3])
array_1d

array([1, 4, 3])

In [10]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [11]:
array_1d

array([1, 4, 3])

In [12]:
array_2d = np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [13]:
array_3d = np.array([[(1, 4, 2), (1,5,9)],[(7, 5, 9), (8, 1, 3)], [(3, 5, 3), (7, 2,9)]], dtype=float)
array_3d

array([[[1., 4., 2.],
        [1., 5., 9.]],

       [[7., 5., 9.],
        [8., 1., 3.]],

       [[3., 5., 3.],
        [7., 2., 9.]]])

In [14]:
print(array_3d)

[[[1. 4. 2.]
  [1. 5. 9.]]

 [[7. 5. 9.]
  [8. 1. 3.]]

 [[3. 5. 3.]
  [7. 2. 9.]]]


### Crando Arrays

In [18]:
# De cerors con 3 filas y 4 columnas
array_ceros = np.zeros((3,4))
array_ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# De unos con 2 dimensiones 4 filas y 5 columnas
np.ones((2, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [23]:
# Intervalo y saltos
np.arange(12,32, 2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [24]:
# Intervalo y divisiones
np.linspace(0, 4, 7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [25]:
# Valor dado
np.full((3, 3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [26]:
# Matriz identidad, diagonal de unos
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Array con valores aleatorios entre 0 y 1
np.random.random((4, 4))

array([[0.39421818, 0.98680524, 0.48246496, 0.95900656],
       [0.10727435, 0.58573859, 0.21218647, 0.43219756],
       [0.58704575, 0.14732761, 0.81075885, 0.19644975],
       [0.18823725, 0.42720894, 0.12951872, 0.07422531]])

In [29]:
# Array vacio de 4 filas y 3 columnas
np.empty((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Grabar y cargar


In [30]:
# Grabar
np.save('mi_array', np.random.random((3,3)))

In [32]:
# Cargar
mi_array = np.load('mi_array.npy')
mi_array

array([[9.72054007e-01, 6.69633724e-01, 9.70406279e-01],
       [5.34245175e-01, 5.22449010e-02, 1.28256100e-01],
       [4.90414498e-01, 9.58195368e-01, 7.40073991e-04]])

In [33]:
# Grabar
np.save('mi_array_3d', array_3d)


In [34]:
# Grabar a fichero de texto
np.savetxt('mi_array.txt', array_2d, delimiter= "")

In [35]:
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [41]:
# Cargar de un fichero de texto
array_2d_txt = np.loadtxt('mi_array.txt', dtype=float)
print(array_2d_txt)

ValueError: ignored

# Tipo de datos

In [42]:
# Enteros
np.int64

numpy.int64

In [43]:
# Decimal, numero doble precision o de punto flotante
np.float64

numpy.float64

In [44]:
# Complejos
np.complex_

numpy.complex128

In [45]:
#Boolean
np.bool_

numpy.bool_

In [46]:
# Objetos
np.object_

numpy.object_

In [47]:
# Cadenas
np.string_

numpy.bytes_

In [48]:
np.unicode_

numpy.str_

# Propiedades y características


In [49]:
array_3d

array([[[1., 4., 2.],
        [1., 5., 9.]],

       [[7., 5., 9.],
        [8., 1., 3.]],

       [[3., 5., 3.],
        [7., 2., 9.]]])

In [50]:
# Dimensiones y forma (dimensiones, filas y columnas)
array_3d.shape

(3, 2, 3)

In [52]:
# Longitud
len(array_3d)

3

In [53]:
# Numero de dimensiones
array_3d.ndim

3

In [54]:
# Tamaño y numero de elementos
array_3d.size

18

In [55]:
# Tipos de datos del array
array_3d.dtype

dtype('float64')

In [56]:
array_3d.dtype.name

'float64'

In [57]:
# Convertir de un tipo a otro
array_3d.astype(int)

array([[[1, 4, 2],
        [1, 5, 9]],

       [[7, 5, 9],
        [8, 1, 3]],

       [[3, 5, 3],
        [7, 2, 9]]])

# Ayuda de Numpy

In [59]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Operadores aritmeticos

In [60]:
# Arrays ejemplo
array1 = np.random.random((4, 4))
array1

array([[0.7779326 , 0.86490529, 0.28287825, 0.39721878],
       [0.05756344, 0.57935936, 0.25338091, 0.80209105],
       [0.24141433, 0.74387377, 0.09200689, 0.59925802],
       [0.9487951 , 0.13725766, 0.0221178 , 0.85566367]])

In [61]:
array2 = np.random.random((4, 4))
array2

array([[0.16826619, 0.70275836, 0.77684942, 0.3454548 ],
       [0.5261061 , 0.09503491, 0.69298208, 0.50170028],
       [0.05748934, 0.45829313, 0.36926031, 0.94735157],
       [0.73294831, 0.74687751, 0.96212353, 0.21515478]])

In [62]:
# Suma de arrays
array3 = array1 + array2
array3

array([[0.94619879, 1.56766366, 1.05972767, 0.74267358],
       [0.58366954, 0.67439427, 0.94636299, 1.30379133],
       [0.29890368, 1.20216691, 0.4612672 , 1.5466096 ],
       [1.68174341, 0.88413517, 0.98424133, 1.07081844]])

In [63]:
# Otra opcion de suma
array_3b = np.add(array1, array2)
array_3b

array([[0.94619879, 1.56766366, 1.05972767, 0.74267358],
       [0.58366954, 0.67439427, 0.94636299, 1.30379133],
       [0.29890368, 1.20216691, 0.4612672 , 1.5466096 ],
       [1.68174341, 0.88413517, 0.98424133, 1.07081844]])

In [64]:
# Resta de arrays
array3 = array1 - array2
array3

array([[ 0.60966641,  0.16214693, -0.49397117,  0.05176398],
       [-0.46854266,  0.48432445, -0.43960117,  0.30039076],
       [ 0.18392499,  0.28558064, -0.27725343, -0.34809355],
       [ 0.21584679, -0.60961985, -0.94000574,  0.64050889]])

In [65]:
# Multiplicacion de arrays
array3 = array1 * array2
array3

array([[0.13089976, 0.60781943, 0.21975381, 0.13722113],
       [0.03028447, 0.05505937, 0.17558843, 0.40240931],
       [0.01387875, 0.34091224, 0.03397449, 0.56770803],
       [0.69541776, 0.10251466, 0.02128005, 0.18410013]])

In [66]:
# Division de arrays
array3 = array1 / array2
array3

array([[4.6232258 , 1.23072927, 0.36413524, 1.14984298],
       [0.10941412, 6.09627925, 0.36563847, 1.59874545],
       [4.19928831, 1.62313968, 0.24916538, 0.63256138],
       [1.29449115, 0.18377533, 0.02298852, 3.976968  ]])

In [67]:
# Multiplicacion de arrays
array3 = np.divide(array1, array2)
array3

array([[4.6232258 , 1.23072927, 0.36413524, 1.14984298],
       [0.10941412, 6.09627925, 0.36563847, 1.59874545],
       [4.19928831, 1.62313968, 0.24916538, 0.63256138],
       [1.29449115, 0.18377533, 0.02298852, 3.976968  ]])

In [68]:
np.exp(array1)

array([[2.17696694, 2.37478117, 1.3269436 , 1.48768137],
       [1.05925246, 1.78489459, 1.28837394, 2.23019951],
       [1.27304839, 2.10407044, 1.09637237, 1.82076733],
       [2.58259602, 1.14712368, 1.02236421, 2.35293543]])

In [72]:
# Seno de un array
np.sin(array1)

array([[0.70180817, 0.76103383, 0.27912066, 0.38685516],
       [0.05753165, 0.54748795, 0.25067834, 0.71881137],
       [0.23907618, 0.6771435 , 0.09187713, 0.56402994],
       [0.81271405, 0.13682708, 0.02211599, 0.75500626]])

In [73]:
# Coseno de un array
np.cos(array1)

array([[0.71236598, 0.64871219, 0.96025604, 0.92214049],
       [0.99834368, 0.83681356, 0.96807044, 0.69520516],
       [0.97100081, 0.73585099, 0.99577035, 0.82575434],
       [0.58266275, 0.99059495, 0.99975541, 0.65571758]])

In [74]:
# Logaritmo de un array
np.log(array1)

array([[-0.25111539, -0.14513527, -1.26273869, -0.92326807],
       [-2.85486771, -0.54583234, -1.37286135, -0.22053315],
       [-1.42124059, -0.29588392, -2.38589184, -0.51206302],
       [-0.05256241, -1.98589541, -3.81137278, -0.15587789]])

In [75]:
array1.dot(array2)

array([[0.89333502, 1.05520977, 1.69032961, 1.05611246],
       [0.91694845, 0.81069904, 1.31147796, 0.72316484],
       [0.87649297, 0.73008838, 1.31356852, 0.67269552],
       [0.860291  , 1.32903034, 1.6636094 , 0.60168148]])

# Comparacion

 == != < > <= >= and or

In [76]:
array1 == array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [77]:
array1 < 0,5

(array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]),
 5)

In [78]:
array1

array([[0.7779326 , 0.86490529, 0.28287825, 0.39721878],
       [0.05756344, 0.57935936, 0.25338091, 0.80209105],
       [0.24141433, 0.74387377, 0.09200689, 0.59925802],
       [0.9487951 , 0.13725766, 0.0221178 , 0.85566367]])

In [80]:
array3 <= 0.4

array([[False, False,  True, False],
       [ True, False,  True, False],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [81]:
array3

array([[4.6232258 , 1.23072927, 0.36413524, 1.14984298],
       [0.10941412, 6.09627925, 0.36563847, 1.59874545],
       [4.19928831, 1.62313968, 0.24916538, 0.63256138],
       [1.29449115, 0.18377533, 0.02298852, 3.976968  ]])

# Estadisticos basicos y otras funciones

In [82]:
def creaArray(fila, columna):
  array = np.random.random((fila,columna))
  return array

In [83]:
array1 = creaArray(5,5)
array1

array([[0.94571175, 0.47620556, 0.24077705, 0.63755436, 0.6718131 ],
       [0.50357629, 0.83356955, 0.81063783, 0.28675648, 0.20959022],
       [0.88388397, 0.37136909, 0.02474153, 0.08006649, 0.29688804],
       [0.62470104, 0.47175999, 0.63495496, 0.46557135, 0.27743497],
       [0.98549812, 0.63306364, 0.62775193, 0.81314652, 0.79508149]])

In [89]:
# Suma de todos los valores
suma_total = array1.sum()
print(suma_total)

13.602105353824275


In [90]:
#Valor Minimo
array1.min()

0.024741530930657563

In [86]:
array1.max()

0.9854981239218924

In [91]:
# Maximo por filas
array1.max(axis=0)

array([0.98549812, 0.83356955, 0.81063783, 0.81314652, 0.79508149])

In [92]:
# Maximo por columnas
array1.max(axis=1)

array([0.94571175, 0.83356955, 0.88388397, 0.63495496, 0.98549812])

In [93]:
# Suma acumulada
array1.cumsum(axis=1)

array([[0.94571175, 1.42191732, 1.66269437, 2.30024874, 2.97206184],
       [0.50357629, 1.33714584, 2.14778367, 2.43454015, 2.64413037],
       [0.88388397, 1.25525305, 1.27999458, 1.36006108, 1.65694911],
       [0.62470104, 1.09646103, 1.731416  , 2.19698735, 2.47442232],
       [0.98549812, 1.61856177, 2.24631369, 3.05946021, 3.85454171]])

In [94]:
# Suma acumulada
array1.cumsum(axis=0)

array([[0.94571175, 0.47620556, 0.24077705, 0.63755436, 0.6718131 ],
       [1.44928804, 1.30977512, 1.05141488, 0.92431085, 0.88140333],
       [2.33317201, 1.6811442 , 1.07615641, 1.00437734, 1.17829136],
       [2.95787305, 2.15290419, 1.71111138, 1.46994869, 1.45572633],
       [3.94337117, 2.78596784, 2.33886331, 2.28309521, 2.25080783]])

In [96]:
# Media
array1.mean()


0.544084214152971

In [97]:
np.mean(array1)

0.544084214152971

In [98]:
# Mediana
np.median(array1)

0.6247010384768968

In [101]:
#Correlacion
np.corrcoef(array1)

array([[ 1.        , -0.59859773,  0.80170132, -0.12715982,  0.94711747],
       [-0.59859773,  1.        , -0.04146686,  0.62707813, -0.61743114],
       [ 0.80170132, -0.04146686,  1.        ,  0.2146129 ,  0.71944254],
       [-0.12715982,  0.62707813,  0.2146129 ,  1.        ,  0.0519917 ],
       [ 0.94711747, -0.61743114,  0.71944254,  0.0519917 ,  1.        ]])

In [102]:
# Desviación estandar
np.std(array1)

0.26468072195492237

# Copiando arrays

In [103]:
array2=np.random.randint(21,size=10)

In [104]:
array2

array([19, 10, 12,  5, 11,  4,  3,  7,  3, 16])

In [105]:
array1 = np.random.randint(21,size=(4,4))

In [106]:
array1

array([[ 4,  7, 11, 11],
       [11,  9,  4,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [107]:
# Crear una imagen del array, el valor cambiado se refjeja en los dos
array_cop = array1.view()
array_cop


array([[ 4,  7, 11, 11],
       [11,  9,  4,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [108]:
np.array_equal(array1, array_cop)

True

In [111]:
# Modificamos un valor de la copia
array_cop[0,1] = 99
array_cop

array([[ 4, 99, 11, 11],
       [11,  9,  4,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [110]:
array1

array([[ 4, 99, 11, 11],
       [11,  9,  4,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [112]:
# Modificamos un valor del original
array1[1,2]=88
array1

array([[ 4, 99, 11, 11],
       [11,  9, 88,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [113]:
array_cop

array([[ 4, 99, 11, 11],
       [11,  9, 88,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [114]:
# Creamos una copia independiente
array_cop2 = np.copy(array1)
array_cop2

array([[ 4, 99, 11, 11],
       [11,  9, 88,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [115]:
array_cop2[2, 3] = 77
array_cop2

array([[ 4, 99, 11, 11],
       [11,  9, 88,  2],
       [ 0,  5,  2, 77],
       [10,  2,  3, 15]])

In [116]:
array_cop

array([[ 4, 99, 11, 11],
       [11,  9, 88,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [117]:
array_cop2 = array1 * 3
array_cop2

array([[ 12, 297,  33,  33],
       [ 33,  27, 264,   6],
       [  0,  15,   6,   9],
       [ 30,   6,   9,  45]])

In [118]:
array_cop2 = array1.copy()
array_cop2

array([[ 4, 99, 11, 11],
       [11,  9, 88,  2],
       [ 0,  5,  2,  3],
       [10,  2,  3, 15]])

In [119]:
np.array_equal(array1, array_cop2)

True

#Arrays, ordenamiento

In [127]:
array_1 = np.random.randint(41, size=(10,10))
array_1

array([[19, 31,  4, 33, 32, 11,  2,  8, 20, 16],
       [37, 31, 38, 32, 27, 29, 23, 34, 35,  5],
       [26,  4, 26, 21,  7, 26, 11,  7, 36, 38],
       [25, 11, 34, 38,  1, 29,  7, 38, 28, 23],
       [24, 13, 32, 31,  2, 35,  6,  8, 36,  3],
       [28, 29, 31, 22,  2,  0, 16, 37, 11,  0],
       [22, 35, 23, 11, 31, 22,  5, 32, 39, 10],
       [38, 22, 21,  2, 26,  3, 28, 10, 13, 24],
       [ 6, 19,  4, 35, 38,  1, 20, 19, 23, 20],
       [27,  6, 23, 37, 35,  8, 40, 14,  3, 12]])

In [122]:
array_2 = np.random.randint(31, size=(10,10))
array_2

array([[14, 22,  5, 10, 30,  1, 10, 28, 25,  4],
       [12, 17, 21, 23,  6, 20,  3,  2, 14,  1],
       [ 4,  0,  7, 16, 10, 27, 14, 29, 11, 15],
       [24, 29, 12,  6, 23,  3, 14,  3, 11, 26],
       [10, 11, 15,  8, 17,  5,  4, 10,  6, 23],
       [11, 10, 13, 28, 19,  2, 11, 21,  1, 16],
       [12,  0,  4, 17, 11,  3, 12, 23,  6, 27],
       [13,  4, 22, 15,  9, 20, 23, 18, 13, 16],
       [28,  7, 27,  3, 22, 24, 16, 26,  7, 29],
       [13, 21,  6, 18, 21, 26, 14, 22, 20,  8]])

In [123]:
array_1

array([[12,  9,  9, 10,  1, 38,  5, 30, 37, 28],
       [11,  8,  2,  8, 19, 32, 39, 30, 19,  1],
       [12, 16, 25, 32, 35, 12, 26,  6,  4,  8],
       [18,  9, 40,  3, 36, 40, 11, 12, 24,  9],
       [38, 30, 22, 36, 38, 30,  3, 15, 22, 27],
       [28,  8, 30, 38, 32, 35, 36, 37,  0,  0],
       [37, 22,  3, 23, 35, 36, 40, 37, 18, 25],
       [ 1, 25, 19,  8, 34, 34,  2, 30, 13, 39],
       [ 1,  6, 30,  2, 28, 32, 23, 20, 28, 38],
       [ 1,  0,  5, 31, 35, 36,  1, 35,  9, 38]])

In [126]:
# Ordenamos el array por filas
array_1.sort()
array_1

array([[ 1,  5,  9,  9, 10, 12, 28, 30, 37, 38],
       [ 1,  2,  8,  8, 11, 19, 19, 30, 32, 39],
       [ 4,  6,  8, 12, 12, 16, 25, 26, 32, 35],
       [ 3,  9,  9, 11, 12, 18, 24, 36, 40, 40],
       [ 3, 15, 22, 22, 27, 30, 30, 36, 38, 38],
       [ 0,  0,  8, 28, 30, 32, 35, 36, 37, 38],
       [ 3, 18, 22, 23, 25, 35, 36, 37, 37, 40],
       [ 1,  2,  8, 13, 19, 25, 30, 34, 34, 39],
       [ 1,  2,  6, 20, 23, 28, 28, 30, 32, 38],
       [ 0,  1,  1,  5,  9, 31, 35, 35, 36, 38]])

In [128]:
array_1.sort(axis=1)
array_1

array([[ 2,  4,  8, 11, 16, 19, 20, 31, 32, 33],
       [ 5, 23, 27, 29, 31, 32, 34, 35, 37, 38],
       [ 4,  7,  7, 11, 21, 26, 26, 26, 36, 38],
       [ 1,  7, 11, 23, 25, 28, 29, 34, 38, 38],
       [ 2,  3,  6,  8, 13, 24, 31, 32, 35, 36],
       [ 0,  0,  2, 11, 16, 22, 28, 29, 31, 37],
       [ 5, 10, 11, 22, 22, 23, 31, 32, 35, 39],
       [ 2,  3, 10, 13, 21, 22, 24, 26, 28, 38],
       [ 1,  4,  6, 19, 19, 20, 20, 23, 35, 38],
       [ 3,  6,  8, 12, 14, 23, 27, 35, 37, 40]])

In [129]:
array_2.sort(axis=0)
array_2

array([[ 4,  0,  4,  3,  6,  1,  3,  2,  1,  1],
       [10,  0,  5,  6,  9,  2,  4,  3,  6,  4],
       [11,  4,  6,  8, 10,  3, 10, 10,  6,  8],
       [12,  7,  7, 10, 11,  3, 11, 18,  7, 15],
       [12, 10, 12, 15, 17,  5, 12, 21, 11, 16],
       [13, 11, 13, 16, 19, 20, 14, 22, 11, 16],
       [13, 17, 15, 17, 21, 20, 14, 23, 13, 23],
       [14, 21, 21, 18, 22, 24, 14, 26, 14, 26],
       [24, 22, 22, 23, 23, 26, 16, 28, 20, 27],
       [28, 29, 27, 28, 30, 27, 23, 29, 25, 29]])

# Subconjuntos indexados

In [131]:
array = np.random.randint(31, size=(10,10))
array

array([[17,  1, 28, 27, 17, 24, 15, 23, 17, 13],
       [10,  3, 17, 28, 17, 29, 28, 21, 18, 22],
       [ 1, 10, 14,  8, 20, 16, 22,  0, 10, 19],
       [24,  0, 25, 13, 12, 14, 18,  0,  0,  0],
       [ 0, 25,  0,  8,  7, 15,  2, 12,  5, 20],
       [27, 25, 13, 22,  6, 30,  7, 22,  5, 12],
       [19, 18, 18, 20, 28, 25, 30,  5, 28,  1],
       [10, 22,  7, 28, 27, 26, 10,  5, 26, 21],
       [ 3, 30, 18, 21, 29, 12, 24,  8, 30, 21],
       [ 7, 13, 17, 16, 25, 29, 15, 25,  4, 11]])

In [132]:
# Seleccionamos elementos de la fila 2, columna 3
array[2,3]


8

In [134]:
# Seleccionar una rebanada (slicing)
array_3filas = array[1:4]
array_3filas

array([[10,  3, 17, 28, 17, 29, 28, 21, 18, 22],
       [ 1, 10, 14,  8, 20, 16, 22,  0, 10, 19],
       [24,  0, 25, 13, 12, 14, 18,  0,  0,  0]])

In [137]:
array[1:4,2:4]

array([[17, 28],
       [14,  8],
       [25, 13]])

In [136]:
array[1:4,2]

array([17, 14, 25])

In [138]:
array[:1]

array([[17,  1, 28, 27, 17, 24, 15, 23, 17, 13]])

In [141]:
array[3:4] # array[3]

array([[24,  0, 25, 13, 12, 14, 18,  0,  0,  0]])

In [142]:
array[:,4:5]

array([[17],
       [17],
       [20],
       [12],
       [ 7],
       [ 6],
       [28],
       [27],
       [29],
       [25]])

In [143]:
array

array([[17,  1, 28, 27, 17, 24, 15, 23, 17, 13],
       [10,  3, 17, 28, 17, 29, 28, 21, 18, 22],
       [ 1, 10, 14,  8, 20, 16, 22,  0, 10, 19],
       [24,  0, 25, 13, 12, 14, 18,  0,  0,  0],
       [ 0, 25,  0,  8,  7, 15,  2, 12,  5, 20],
       [27, 25, 13, 22,  6, 30,  7, 22,  5, 12],
       [19, 18, 18, 20, 28, 25, 30,  5, 28,  1],
       [10, 22,  7, 28, 27, 26, 10,  5, 26, 21],
       [ 3, 30, 18, 21, 29, 12, 24,  8, 30, 21],
       [ 7, 13, 17, 16, 25, 29, 15, 25,  4, 11]])

In [145]:
# Array al reves que estaba en el original
array[::-1]

array([[ 7, 13, 17, 16, 25, 29, 15, 25,  4, 11],
       [ 3, 30, 18, 21, 29, 12, 24,  8, 30, 21],
       [10, 22,  7, 28, 27, 26, 10,  5, 26, 21],
       [19, 18, 18, 20, 28, 25, 30,  5, 28,  1],
       [27, 25, 13, 22,  6, 30,  7, 22,  5, 12],
       [ 0, 25,  0,  8,  7, 15,  2, 12,  5, 20],
       [24,  0, 25, 13, 12, 14, 18,  0,  0,  0],
       [ 1, 10, 14,  8, 20, 16, 22,  0, 10, 19],
       [10,  3, 17, 28, 17, 29, 28, 21, 18, 22],
       [17,  1, 28, 27, 17, 24, 15, 23, 17, 13]])

#Manipulación de arrays


In [146]:
array = np.random.randint(10, size=(5, 5))
array

array([[8, 4, 3, 7, 4],
       [4, 5, 8, 4, 3],
       [3, 2, 0, 5, 6],
       [5, 1, 1, 1, 1],
       [1, 0, 7, 5, 8]])

In [147]:
# Transpuesta
array_t = np.transpose(array)
array_t

array([[8, 4, 3, 5, 1],
       [4, 5, 2, 1, 0],
       [3, 8, 0, 1, 7],
       [7, 4, 5, 1, 5],
       [4, 3, 6, 1, 8]])

In [148]:
# Aplanar el array
array.ravel()

array([8, 4, 3, 7, 4, 4, 5, 8, 4, 3, 3, 2, 0, 5, 6, 5, 1, 1, 1, 1, 1, 0,
       7, 5, 8])

In [149]:
# Cambiamos la forma pero no los datos
array.reshape(5,5)

array([[8, 4, 3, 7, 4],
       [4, 5, 8, 4, 3],
       [3, 2, 0, 5, 6],
       [5, 1, 1, 1, 1],
       [1, 0, 7, 5, 8]])

In [150]:
array.reshape(25, 1)

array([[8],
       [4],
       [3],
       [7],
       [4],
       [4],
       [5],
       [8],
       [4],
       [3],
       [3],
       [2],
       [0],
       [5],
       [6],
       [5],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [7],
       [5],
       [8]])

In [151]:
array.reshape(1, 25)

array([[8, 4, 3, 7, 4, 4, 5, 8, 4, 3, 3, 2, 0, 5, 6, 5, 1, 1, 1, 1, 1, 0,
        7, 5, 8]])

In [152]:
array = np.random.randint(10, size=(4, 24))
array

array([[1, 8, 2, 5, 2, 6, 5, 6, 9, 0, 8, 4, 4, 8, 1, 8, 0, 1, 9, 7, 5, 4,
        5, 6],
       [0, 9, 2, 8, 8, 2, 2, 1, 3, 0, 5, 9, 8, 9, 2, 0, 6, 0, 1, 1, 6, 0,
        4, 4],
       [8, 7, 1, 3, 6, 7, 7, 2, 4, 0, 8, 7, 0, 2, 2, 9, 7, 0, 4, 0, 5, 3,
        4, 2],
       [4, 8, 1, 4, 2, 4, 9, 9, 6, 8, 9, 2, 6, 5, 6, 8, 9, 1, 6, 4, 7, 3,
        7, 8]])

In [153]:
array.reshape(12,8)


array([[1, 8, 2, 5, 2, 6, 5, 6],
       [9, 0, 8, 4, 4, 8, 1, 8],
       [0, 1, 9, 7, 5, 4, 5, 6],
       [0, 9, 2, 8, 8, 2, 2, 1],
       [3, 0, 5, 9, 8, 9, 2, 0],
       [6, 0, 1, 1, 6, 0, 4, 4],
       [8, 7, 1, 3, 6, 7, 7, 2],
       [4, 0, 8, 7, 0, 2, 2, 9],
       [7, 0, 4, 0, 5, 3, 4, 2],
       [4, 8, 1, 4, 2, 4, 9, 9],
       [6, 8, 9, 2, 6, 5, 6, 8],
       [9, 1, 6, 4, 7, 3, 7, 8]])

In [154]:
# Otra forma
array.resize((8,12))
array

array([[1, 8, 2, 5, 2, 6, 5, 6, 9, 0, 8, 4],
       [4, 8, 1, 8, 0, 1, 9, 7, 5, 4, 5, 6],
       [0, 9, 2, 8, 8, 2, 2, 1, 3, 0, 5, 9],
       [8, 9, 2, 0, 6, 0, 1, 1, 6, 0, 4, 4],
       [8, 7, 1, 3, 6, 7, 7, 2, 4, 0, 8, 7],
       [0, 2, 2, 9, 7, 0, 4, 0, 5, 3, 4, 2],
       [4, 8, 1, 4, 2, 4, 9, 9, 6, 8, 9, 2],
       [6, 5, 6, 8, 9, 1, 6, 4, 7, 3, 7, 8]])

In [155]:
# Añadir / eliminar elementos
np.append(array, 34)

array([ 1,  8,  2,  5,  2,  6,  5,  6,  9,  0,  8,  4,  4,  8,  1,  8,  0,
        1,  9,  7,  5,  4,  5,  6,  0,  9,  2,  8,  8,  2,  2,  1,  3,  0,
        5,  9,  8,  9,  2,  0,  6,  0,  1,  1,  6,  0,  4,  4,  8,  7,  1,
        3,  6,  7,  7,  2,  4,  0,  8,  7,  0,  2,  2,  9,  7,  0,  4,  0,
        5,  3,  4,  2,  4,  8,  1,  4,  2,  4,  9,  9,  6,  8,  9,  2,  6,
        5,  6,  8,  9,  1,  6,  4,  7,  3,  7,  8, 34])

In [156]:
# Añadir un elemento en el índice 2
array = np.insert(array, 2, 99)
array

array([ 1,  8, 99,  2,  5,  2,  6,  5,  6,  9,  0,  8,  4,  4,  8,  1,  8,
        0,  1,  9,  7,  5,  4,  5,  6,  0,  9,  2,  8,  8,  2,  2,  1,  3,
        0,  5,  9,  8,  9,  2,  0,  6,  0,  1,  1,  6,  0,  4,  4,  8,  7,
        1,  3,  6,  7,  7,  2,  4,  0,  8,  7,  0,  2,  2,  9,  7,  0,  4,
        0,  5,  3,  4,  2,  4,  8,  1,  4,  2,  4,  9,  9,  6,  8,  9,  2,
        6,  5,  6,  8,  9,  1,  6,  4,  7,  3,  7,  8])

In [157]:
# Borrado de un elemento
array = np.delete(array, [1])
array

array([ 1, 99,  2,  5,  2,  6,  5,  6,  9,  0,  8,  4,  4,  8,  1,  8,  0,
        1,  9,  7,  5,  4,  5,  6,  0,  9,  2,  8,  8,  2,  2,  1,  3,  0,
        5,  9,  8,  9,  2,  0,  6,  0,  1,  1,  6,  0,  4,  4,  8,  7,  1,
        3,  6,  7,  7,  2,  4,  0,  8,  7,  0,  2,  2,  9,  7,  0,  4,  0,
        5,  3,  4,  2,  4,  8,  1,  4,  2,  4,  9,  9,  6,  8,  9,  2,  6,
        5,  6,  8,  9,  1,  6,  4,  7,  3,  7,  8])

In [158]:
array_1 = np.random.randint(10, size=(4,4))
array_1

array([[4, 1, 7, 7],
       [1, 4, 8, 1],
       [0, 2, 9, 5],
       [4, 8, 4, 7]])

In [159]:
array_2 = np.random.randint(10, size=(4,4))
array_2

array([[0, 5, 1, 7],
       [8, 3, 3, 5],
       [1, 4, 6, 2],
       [6, 1, 3, 4]])

In [160]:
# Combinar arrays
array_combinado = np.concatenate((array_1, array_2), axis=0)
array_combinado

array([[4, 1, 7, 7],
       [1, 4, 8, 1],
       [0, 2, 9, 5],
       [4, 8, 4, 7],
       [0, 5, 1, 7],
       [8, 3, 3, 5],
       [1, 4, 6, 2],
       [6, 1, 3, 4]])

In [162]:
# Array vertical
array_combinado = np.vstack((array_1, array_2))
array_combinado

array([[4, 1, 7, 7],
       [1, 4, 8, 1],
       [0, 2, 9, 5],
       [4, 8, 4, 7],
       [0, 5, 1, 7],
       [8, 3, 3, 5],
       [1, 4, 6, 2],
       [6, 1, 3, 4]])

In [164]:
# Otra forma
array_combinado = np.r_[array_1, array_2]
array_combinado

array([[4, 1, 7, 7],
       [1, 4, 8, 1],
       [0, 2, 9, 5],
       [4, 8, 4, 7],
       [0, 5, 1, 7],
       [8, 3, 3, 5],
       [1, 4, 6, 2],
       [6, 1, 3, 4]])

In [166]:
# Combinado Horizontalmente
array_combinado = np.hstack((array_1, array_2))
array_combinado

array([[4, 1, 7, 7, 0, 5, 1, 7],
       [1, 4, 8, 1, 8, 3, 3, 5],
       [0, 2, 9, 5, 1, 4, 6, 2],
       [4, 8, 4, 7, 6, 1, 3, 4]])

In [167]:
# Otra forma
np.column_stack((array_1, array_2))

array([[4, 1, 7, 7, 0, 5, 1, 7],
       [1, 4, 8, 1, 8, 3, 3, 5],
       [0, 2, 9, 5, 1, 4, 6, 2],
       [4, 8, 4, 7, 6, 1, 3, 4]])

In [168]:
# Otra forma
array_combinado = np.c_[array_1, array_2]
array_combinado

array([[4, 1, 7, 7, 0, 5, 1, 7],
       [1, 4, 8, 1, 8, 3, 3, 5],
       [0, 2, 9, 5, 1, 4, 6, 2],
       [4, 8, 4, 7, 6, 1, 3, 4]])

In [169]:
# Splitting, corte array verticalmente
np.vsplit(array_1, 2)

[array([[4, 1, 7, 7],
        [1, 4, 8, 1]]),
 array([[0, 2, 9, 5],
        [4, 8, 4, 7]])]

In [170]:
array_1

array([[4, 1, 7, 7],
       [1, 4, 8, 1],
       [0, 2, 9, 5],
       [4, 8, 4, 7]])

In [171]:
# Corte horizontal
np.hsplit(array_1, 2)

[array([[4, 1],
        [1, 4],
        [0, 2],
        [4, 8]]),
 array([[7, 7],
        [8, 1],
        [9, 5],
        [4, 7]])]