In [1]:
import numpy as np

Crea un array con elementos del 20 al 60 inclusives

In [4]:
#array = np.random.randint(21, 61,30)
array = np.arange(20, 61, 1)
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

Crea un array de una dimension con 15 elementos de unos, luego cambiar el tercer elemento a 99

In [6]:
array = np.ones((1, 15))
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
array[0,2] = 99
array

array([[ 1.,  1., 99.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.]])

Crea una matriz de 6 * 6 de ceros

In [8]:
array = np.zeros((6,6))
array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Convertir el tipo de datos anterior a entero





In [9]:
array.dtype.name

'float64'

In [11]:
array.dtype = "int64"
array.dtype.name

'int64'

In [12]:
array


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

Crea un array de numeros enteros del 1 al 20 inclusives, con 4 filas y 3 columnas, muestra el valor de la segunda fila y primera columna

In [17]:
array = np.random.randint(1, 21, size=12)
array

array([12,  4, 14,  1, 19,  8, 19, 18,  4, 12, 13, 16])

In [18]:
array = array.reshape(4,3)
array

array([[12,  4, 14],
       [ 1, 19,  8],
       [19, 18,  4],
       [12, 13, 16]])

In [19]:
array[1,0]

1

Crea un array con valores del rango 50 a 99 inclusives

In [20]:
array = np.arange(50, 100)
array

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Invierte el array anterior

In [21]:
array[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

Crea una matriz 4 * 4 con valores de 1 a 16

In [22]:
array = np.arange(1, 17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Encontrar los valores mayores a 6 del array anterior

In [23]:
array_sup_6 = array[array>6]
array_sup_6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Crear una matriz identidad de 5 * 5

In [24]:
array = np.identity(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Crear matriz con valores al azar entre 0 y 1 de forma 4x4x4

In [25]:
array = np.random.random((4,4,4))
array

array([[[0.42510161, 0.01318051, 0.49079554, 0.14434502],
        [0.15869611, 0.25443066, 0.92551968, 0.19343221],
        [0.14966345, 0.96722433, 0.5767356 , 0.67812008],
        [0.47396859, 0.27626975, 0.485658  , 0.89206156]],

       [[0.16502016, 0.69031058, 0.6571106 , 0.21775432],
        [0.89528718, 0.61591157, 0.19405675, 0.90874721],
        [0.37269124, 0.8455448 , 0.61876802, 0.33189241],
        [0.66190786, 0.807708  , 0.68754498, 0.45583225]],

       [[0.02226025, 0.56930854, 0.74412363, 0.57119086],
        [0.97879584, 0.09022095, 0.90009411, 0.47603513],
        [0.89807594, 0.55070708, 0.73598239, 0.09232159],
        [0.57389803, 0.00153186, 0.61989852, 0.23379942]],

       [[0.51530757, 0.6155744 , 0.08243167, 0.2826787 ],
        [0.02799065, 0.60457228, 0.53840522, 0.99342469],
        [0.04625902, 0.01561391, 0.86566985, 0.06262284],
        [0.47352849, 0.69034488, 0.20204833, 0.4139112 ]]])

Indicar valor minimo y maximo del array anterior y su posicion


In [26]:
array.min()

0.001531859158332538

In [27]:
array.argmin()

45

In [28]:
array.max()

0.9934246935036316

In [29]:
array.argmax()

55

Crear 2 arrays al azar y verificar si son iguales

In [30]:
array1 = np.random.random((5,5))
array1

array([[0.01966302, 0.55868332, 0.00230915, 0.16127088, 0.63288715],
       [0.1588689 , 0.04437818, 0.29904544, 0.86813102, 0.81730929],
       [0.58240011, 0.37751494, 0.89418421, 0.27790187, 0.77712917],
       [0.58354343, 0.0934739 , 0.36584015, 0.82216003, 0.82667703],
       [0.90217644, 0.55706902, 0.0413219 , 0.11564261, 0.94725714]])

In [31]:
array2 = np.random.random((5,5))
array2

array([[0.16125496, 0.42570161, 0.68421397, 0.96031584, 0.81277959],
       [0.52922874, 0.75549722, 0.69986862, 0.27918032, 0.25440708],
       [0.15649802, 0.58169569, 0.92618899, 0.48818225, 0.52345805],
       [0.57160357, 0.76616079, 0.14185964, 0.5366725 , 0.63373527],
       [0.73040354, 0.15438859, 0.0539004 , 0.26717861, 0.84853128]])

In [32]:
array1 == array2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [33]:
np.array_equal(array1,array2)

False

De uno de los arrays anteriores obten la media y muestra los valores que estan por encima de la media

In [34]:
media = array1.mean()
media

0.46907353166301563

In [35]:
array1[array1 > media]


array([0.55868332, 0.63288715, 0.86813102, 0.81730929, 0.58240011,
       0.89418421, 0.77712917, 0.58354343, 0.82216003, 0.82667703,
       0.90217644, 0.55706902, 0.94725714])

In [36]:
array1

array([[0.01966302, 0.55868332, 0.00230915, 0.16127088, 0.63288715],
       [0.1588689 , 0.04437818, 0.29904544, 0.86813102, 0.81730929],
       [0.58240011, 0.37751494, 0.89418421, 0.27790187, 0.77712917],
       [0.58354343, 0.0934739 , 0.36584015, 0.82216003, 0.82667703],
       [0.90217644, 0.55706902, 0.0413219 , 0.11564261, 0.94725714]])